module "cluster" {
    source = "./cluster"
    KUBE_CONFIG_PATH = var.KUBE_CONFIG_PATH
}

module "deployments" {
    depends_on = [
      module.cluster
    ]
    
    source = "./deployments"

    CLOUDFLARE_EMAIL = var.CLOUDFLARE_EMAIL
    CLOUDFLARE_API_KEY = var.CLOUDFLARE_API_KEY
    CLOUDFLARE_ZONE_ID = var.CLOUDFLARE_ZONE_ID
    DOMAIN = var.DOMAIN
    REGISTRY_SERVER = var.REGISTRY_SERVER
    REGISTRY_USERNAME = var.REGISTRY_USERNAME
    REGISTRY_PASSWORD = var.REGISTRY_PASSWORD
    S3_ENDPOINT = var.S3_ENDPOINT
    S3_BUCKET = var.S3_BUCKET
    S3_ACCESS_KEY = var.S3_ACCESS_KEY
    S3_SECRET_KEY = var.S3_SECRET_KEY
    DB_IP = var.DB_IP
    DB_PORT = var.DB_PORT
    DB_NAME = var.DB_NAME
    DB_AUTHSOURCE = var.DB_AUTHSOURCE
    DB_USERNAME = var.DB_USERNAME
    DB_PASSWORD = var.DB_PASSWORD
    MAIL_HOST = var.MAIL_HOST
    MAIL_PORT = var.MAIL_PORT
    MAIL_POSTMASTER = var.MAIL_POSTMASTER
    MAIL_POSTMASTER_PASSWORD = var.MAIL_POSTMASTER_PASSWORD
    MAIL_FROM_EMAIL = var.MAIL_FROM_EMAIL
    MAIL_CONTACT_EMAIL = var.MAIL_CONTACT_EMAIL
    GOOGLE_MAP_API = var.GOOGLE_MAP_API
    GOOGLE_PLACE_API = var.GOOGLE_PLACE_API
    PROVIDER_TYPE = var.PROVIDER_TYPE
    SECRET = var.SECRET
    REFRESH_TOKEN_SECRET = var.REFRESH_TOKEN_SECRET
    ACCESS_TOKEN_SECRET = var.ACCESS_TOKEN_SECRET
    BASE_URL = var.BASE_URL
    API_URL = var.API_URL
    TZ = var.TZ
    MONGO_VOLUME_SIZE = var.MONGO_VOLUME_SIZE
    MONGO_REPLICA_COUNT = var.MONGO_REPLICA_COUNT
    MINIO_VOLUME_SIZE = var.MINIO_VOLUME_SIZE
    MINIO_REPLICA_COUNT = var.MINIO_REPLICA_COUNT
}